[build]
  base = "frontend"
  publish = "build"
  command = "npm ci && CI=false npm run build"

[build.environment]
  NODE_VERSION = "18"

# All routes to React app (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 