[build]
  publish = "."
  command = "npm run build"

[[redirects]]
  from = "/frontend/*"
  to = "/frontend/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "http://localhost:3001/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 