[build]
  base = "."
  publish = "frontend/build"
  command = "cd frontend && npm install && npm run build"

# Handle routes for the React application
[[redirects]]
  from = "/login"
  to = "/frontend/build/index.html"
  status = 200

[[redirects]]
  from = "/signup"
  to = "/frontend/build/index.html"
  status = 200

[[redirects]]
  from = "/dashboard"
  to = "/frontend/build/index.html"
  status = 200

[[redirects]]
  from = "/forgot-password"
  to = "/frontend/build/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

# Fallback for all other routes to the main site
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 