[build]
  base = "."
  publish = "frontend/build"
  command = "npm run netlify:build"
  ignore_errors = true
  
[build.environment]
  NODE_VERSION = "18.15.0"
  NPM_VERSION = "9.5.0"
  NETLIFY_USE_YARN = "false"

# API routes
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

# React app routes
[[redirects]]
  from = "/login"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/signup"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/dashboard"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/forgot-password"
  to = "/index.html"
  status = 200

# Fallback to index
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 