[build]
  base = "."
  publish = "frontend/build"
  command = "cd frontend && npm install && DISABLE_ESLINT_PLUGIN=true CI=false npm run build"
  
[build.environment]
  NODE_VERSION = "18.15.0"
  NPM_VERSION = "9.5.0"
  CI = "false"
  ESLINT_NO_DEV_ERRORS = "true"
  DISABLE_ESLINT_PLUGIN = "true"

# All routes to React app (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 